runtime: python27
api_version: 1
threadsafe: true

handlers:
  - url: /
    static_files: dist/wi-app/index.html
    upload: dist/(.*)/(.*)
  -url: /
    static_dir: dist/wi-app

skip_files:
  - e2e/
  - node_modules/
  - src
  - ^(.*/)?\..*$
  - ^(.*/)?\.*\.json$
  - ^(.*/)?\.*\.md$
  - ^(.*/)?\.*\.yaml$
  - ^LICENSE

